[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['md']

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

# =============
# ==  ruby   ==
# =============

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['rb']

[[plugins]]
repo  = 'tpope/vim-rails'
on_ft = ['rb']

# =============
# ==   php   ==
# =============

[[plugins]]
repo = 'joonty/vdebug'
on_ft = ['php']

# =============
# ==  html   ==
# =============

[[plugins]]
repo = 'gregsexton/MatchTag'
on_path = 'html'

# ==============
# ==   pug    ==
# ==============
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug']

# ==============
# ==  golang  ==
# ==============
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_fmt_command = "goimports"
'''

# ==================
# ==   terraform  ==
# ==================
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf']
hook_add = '''
  let g:terraform_align=1
  let g:terraform_fmt_on_save=1
'''

# =============
# ==   js    ==
# =============

# [[plugins]]
# repo = 'othree/yajs.vim'
# on_ft = ['javascript']

# =============
# ==   ts    ==
# =============
[[plugins]]
repo = 'leafgarland/typescript-vim'
# on_ft = ['ts', 'jsx', 'tsx']

# [[plugins]]
# repo = 'mxw/vim-jsx'
#
[[plugins]]
repo = 'pangloss/vim-javascript'

# [[plugins]]
# repo = 'peitalin/vim-jsx-typescript'
# on_ft = ['ts', 'jsx', 'tsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

# ===============
# ==  graphql  ==
# ===============
# [[plugins]]
# repo = 'jparise/vim-graphql'
